version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/factorialDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile  
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: factorialDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
