create table metric
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255)     not null,
    timestamp timestamp(6)     not null,
    value     double precision not null
);

-- alter table metric
--     owner to "user";
--
