name: Run Tests backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-backend:latest ./backend

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-backend:latest
