# Test workflow
name: Build and Push Docker Images

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if backend changed
        id: backend
        run: echo "::set-output name=backend::$(git diff --name-only HEAD^ HEAD | grep -q '^backend/' && echo true || echo false)"

      - name: Set up JDK 17
        if: steps.backend.outputs.backend == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        if: steps.backend.outputs.backend == 'true'
        working-directory: ./backend
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        if: steps.backend.outputs.backend == 'true'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-backend:latest ./backend

      - name: Log in to Docker Hub
        if: steps.backend.outputs.backend == 'true'
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        if: steps.backend.outputs.backend == 'true'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-backend:latest

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if frontend changed
        id: frontend
        run: echo "::set-output name=frontend::$(git diff --name-only HEAD^ HEAD | grep -q '^frontend/' && echo true || echo false)"

      - name: Set up Node.js
        if: steps.frontend.outputs.frontend == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        if: steps.frontend.outputs.frontend == 'true'
        working-directory: ./frontend
        run: npm install

      - name: Build with npm
        if: steps.frontend.outputs.frontend == 'true'
        working-directory: ./frontend
        run: npm run build

      - name: Run tests with npm
        if: steps.frontend.outputs.frontend == 'true'
        working-directory: ./frontend
        run: npm test

      - name: Build Docker image
        if: steps.frontend.outputs.frontend == 'true'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-frontend:latest ./frontend

      - name: Log in to Docker Hub
        if: steps.frontend.outputs.frontend == 'true'
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        if: steps.frontend.outputs.frontend == 'true'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/factorial-metrics-frontend:latest
